### ISSUE TITLE
Code examples?

### ISSUE THREAD

**Issue by decentral1se** [pushcx/hpffp-resources#1]
Thanks for putting this together!

Have you found somewhere that has all the code examples from the chapters?

Maybe we could start to put that here?

**Comment by pushcx** [comment]
I haven't seen anything like that and wouldn't accept a PR for it. I want this repo to collect the available external resources (a task I can finish) rather than be a be-all study aid (an open, infinitely large obligation).

In any case, I think retyping the examples is invaluable for learning. On the rare occasion I've done a copy + paste from the pdf I've only lost indentation, which is one editor command to fix (`=` in vim).

**Comment by decentral1se** [comment]
Fair enough.

**Comment by bitemyapp** [comment]
@lwm 
![screenshot from 2016-08-15 18-25-49](https://cloud.githubusercontent.com/assets/320177/17683083/b930ccfc-6315-11e6-992d-91223e3c0e53.png)

![screenshot from 2016-08-15 18-25-53](https://cloud.githubusercontent.com/assets/320177/17683086/bce25d16-6315-11e6-97be-1adf19a00dcf.png)

![screenshot from 2016-08-15 18-25-55](https://cloud.githubusercontent.com/assets/320177/17683087/bf80783c-6315-11e6-8c9d-6305d53ee250.png)

![watching_you](https://cloud.githubusercontent.com/assets/320177/17683067/a0e5f2c6-6315-11e6-8b35-7cfb4e018af6.gif)

**Comment by decentral1se** [comment]
@bitemyapp :)
